### PR TITLE
Add tests for Repeat<>. Change Repeat<> to 0...inf, because other cas…

### PR DESCRIPTION
**Pull request by tonyastolfi**
…es can be built from primitives.

---
This change is [Reviewable](https://reviewable.io/reviews/hittop/hittop/3)

### CODE REVIEW

**Comment by hittop** [comment]
Good design choice on Repeat!  I like that you're going minimal on the semantics of primitives.  It'll be interesting to see how the generated code might be affected.  I suspect the LLVM optimizer will make short work of all of this ;-)

Try to pay a bit more attention to test names/code repetition when copy-pasting from existing tests.  It's nice to have a set of canonical test cases,  but the test point names should reflect the behavior of the new parser type.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[hittop/parser/repeat-test.cc, line 19 at r1](https://reviewable.io:443/reviews/hittop/hittop/3#-K_OrN2oRAXasRI8N7n9:-K_OrN2oRAXasRI8N7nA:b-d6fc2n) ([raw file](https://github.com/hittop/hittop/blob/60f16a307666fbe00182d528c8b3ee918804977c/hittop/parser/repeat-test.cc#L19)):*
> ```cpp
> using hittop::parser::ParseError;
> 
> using ab_grammar = Concat<Literal<'a'>, Literal<'b'>>;
> ```

The stuff shared from concat-test.cc could be single sourced...

---

*[hittop/parser/repeat-test.cc, line 32 at r1](https://reviewable.io:443/reviews/hittop/hittop/3#-K_Orl1R3u7d7EMCma4r:-K_Orl1R3u7d7EMCma4s:b-l0ohd6) ([raw file](https://github.com/hittop/hittop/blob/60f16a307666fbe00182d528c8b3ee918804977c/hittop/parser/repeat-test.cc#L32)):*
> ```cpp
>  // namespace
> 
> TEST(ParseRepeat, OkPrefix) {
> ```

OkPrefix => OkSingle

---

*[hittop/parser/repeat-test.cc, line 38 at r1](https://reviewable.io:443/reviews/hittop/hittop/3#-K_Orgs3__L9ZTEE-zHX:-K_Orgs3__L9ZTEE-zHY:bk3owwz) ([raw file](https://github.com/hittop/hittop/blob/60f16a307666fbe00182d528c8b3ee918804977c/hittop/parser/repeat-test.cc#L38)):*
> ```cpp
> }
> 
> TEST(ParseRepeat, OkFull) {
> ```

Bad name.

---

*[hittop/parser/repeat-test.cc, line 53 at r1](https://reviewable.io:443/reviews/hittop/hittop/3#-K_OrvJqW1NPyEgEnIR0:-K_OrvJqW1NPyEgEnIR1:b-pz5rhj) ([raw file](https://github.com/hittop/hittop/blob/60f16a307666fbe00182d528c8b3ee918804977c/hittop/parser/repeat-test.cc#L53)):*
> ```cpp
> }
> 
> TEST(ParseRepeat, IncompleteFirstConsumesAll) {
> ```

=> IncompleteZeroComplete

---

*[hittop/parser/repeat-test.cc, line 59 at r1](https://reviewable.io:443/reviews/hittop/hittop/3#-K_Os1FN6PUQcZn42oZP:-K_Os1FN6PUQcZn42oZQ:bcu5pz1) ([raw file](https://github.com/hittop/hittop/blob/60f16a307666fbe00182d528c8b3ee918804977c/hittop/parser/repeat-test.cc#L59)):*
> ```cpp
> }
> 
> TEST(ParseRepeat, BadCharFirst) {
> ```

=> OkZeroErrorOnFirstChar

---

*[hittop/parser/repeat-test.cc, line 67 at r1](https://reviewable.io:443/reviews/hittop/hittop/3#-K_Os64uw_V5Fz9JaZQc:-K_Os64uw_V5Fz9JaZQd:b-i4cd71) ([raw file](https://github.com/hittop/hittop/blob/60f16a307666fbe00182d528c8b3ee918804977c/hittop/parser/repeat-test.cc#L67)):*
> ```cpp
> }
> 
> TEST(ParseRepeat, BadCharSecond) {
> ```

=> OkZeroErrorOnSecondChar

---

*[hittop/parser/repeat-test.cc, line 74 at r1](https://reviewable.io:443/reviews/hittop/hittop/3#-K_OsN9Q_MYX9mpxVLsh:-K_OsN9Q_MYX9mpxVLsi:b-vvrge6) ([raw file](https://github.com/hittop/hittop/blob/60f16a307666fbe00182d528c8b3ee918804977c/hittop/parser/repeat-test.cc#L74)):*
> ```cpp
> }
> 
> TEST(ParseRepeat, MoreThan2Parts) {
> ```

IncompleteMany

---

*[hittop/parser/repeat-test.cc, line 81 at r1](https://reviewable.io:443/reviews/hittop/hittop/3#-K_OsR-w_a83GI4VTbbU:-K_OsR-w_a83GI4VTbbV:bxcmeo0) ([raw file](https://github.com/hittop/hittop/blob/60f16a307666fbe00182d528c8b3ee918804977c/hittop/parser/repeat-test.cc#L81)):*
> ```cpp
> }
> 
> TEST(ParseRepeat, MoreThan2PartsDone) {
> ```

OkMany

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hittop/hittop/3#-:-K_OsUixrt_TkVzsg3tt:b-zey9t8)*

**Comment by tonyastolfi** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[hittop/parser/repeat-test.cc, line 19 at r1](https://reviewable.io:443/reviews/hittop/hittop/3#-K_OrN2oRAXasRI8N7n9:-K_OtOR_-biy9tqz0vTX:bxarkov) ([raw file](https://github.com/hittop/hittop/blob/60f16a307666fbe00182d528c8b3ee918804977c/hittop/parser/repeat-test.cc#L19)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

The stuff shared from concat-test.cc could be single sourced...
</blockquote></details>

I'll rename, but would prefer to keep the tests self-contained.  I think there's a real readability cost from separating test data from logic even more.  

---

*[hittop/parser/repeat-test.cc, line 32 at r1](https://reviewable.io:443/reviews/hittop/hittop/3#-K_Orl1R3u7d7EMCma4r:-K_OvZ6qxBmy9E9R7ZGF:b-896fix) ([raw file](https://github.com/hittop/hittop/blob/60f16a307666fbe00182d528c8b3ee918804977c/hittop/parser/repeat-test.cc#L32)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

OkPrefix => OkSingle
</blockquote></details>

Done.

---

*[hittop/parser/repeat-test.cc, line 38 at r1](https://reviewable.io:443/reviews/hittop/hittop/3#-K_Orgs3__L9ZTEE-zHX:-K_OuvvSCwVg1llKdNjU:bkgubyo) ([raw file](https://github.com/hittop/hittop/blob/60f16a307666fbe00182d528c8b3ee918804977c/hittop/parser/repeat-test.cc#L38)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

Bad name.
</blockquote></details>

Feel free to offer a suggestion for a better one next time ;-)

---

*[hittop/parser/repeat-test.cc, line 53 at r1](https://reviewable.io:443/reviews/hittop/hittop/3#-K_OrvJqW1NPyEgEnIR0:-K_OvCbTp-sf372wW-bH:b-896fix) ([raw file](https://github.com/hittop/hittop/blob/60f16a307666fbe00182d528c8b3ee918804977c/hittop/parser/repeat-test.cc#L53)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

=> IncompleteZeroComplete
</blockquote></details>

Done.

---

*[hittop/parser/repeat-test.cc, line 59 at r1](https://reviewable.io:443/reviews/hittop/hittop/3#-K_Os1FN6PUQcZn42oZP:-K_OvHdbv-nRQfT_9fMn:b-896fix) ([raw file](https://github.com/hittop/hittop/blob/60f16a307666fbe00182d528c8b3ee918804977c/hittop/parser/repeat-test.cc#L59)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

=> OkZeroErrorOnFirstChar
</blockquote></details>

Done.

---

*[hittop/parser/repeat-test.cc, line 67 at r1](https://reviewable.io:443/reviews/hittop/hittop/3#-K_Os64uw_V5Fz9JaZQc:-K_OvL3VNm8OYMTiysRz:b-896fix) ([raw file](https://github.com/hittop/hittop/blob/60f16a307666fbe00182d528c8b3ee918804977c/hittop/parser/repeat-test.cc#L67)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

=> OkZeroErrorOnSecondChar
</blockquote></details>

Done.

---

*[hittop/parser/repeat-test.cc, line 74 at r1](https://reviewable.io:443/reviews/hittop/hittop/3#-K_OsN9Q_MYX9mpxVLsh:-K_OvPralSI_YpIoa1p_:b-896fix) ([raw file](https://github.com/hittop/hittop/blob/60f16a307666fbe00182d528c8b3ee918804977c/hittop/parser/repeat-test.cc#L74)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

IncompleteMany
</blockquote></details>

Done.

---

*[hittop/parser/repeat-test.cc, line 81 at r1](https://reviewable.io:443/reviews/hittop/hittop/3#-K_OsR-w_a83GI4VTbbU:-K_OvRyCnHbN3Jus0j7E:b-896fix) ([raw file](https://github.com/hittop/hittop/blob/60f16a307666fbe00182d528c8b3ee918804977c/hittop/parser/repeat-test.cc#L81)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

OkMany
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hittop/hittop/3)*

**Comment by hittop** [comment]
Did you mean to push a new diff along with these changes??

---

Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hittop/hittop/3#-:-K_OvgzjmI4YY2le4v6B:b-xhubey)*

**Comment by tonyastolfi** [comment]
Oh yeah, whoops!  Should be good now...

---

Review status: 2 of 3 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hittop/hittop/3#-:-K_Ovn7aXr-v7CTYcOOF:ble6ew7)*

**Comment by hittop** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hittop/hittop/3#-:-K_U_U3mgazuaVQ3jceN:bnfp4nl)*

**Pull request merged**
