### PR TITLE
Add semantic actions to the parser; add concurrency package; split out JSON-related code to hittop/json

### PR DESCRIPTION
**Pull request by tonyastolfi**
This change is [Reviewable](https://reviewable.io/reviews/hittop/hittop/8)

### CODE REVIEW

**Comment by hittop** [comment]
Reviewed 50 of 50 files at r1.
Review status: all files reviewed at latest revision, 26 unresolved discussions.

---

*[hittop/concurrent/async_queue-test.cc, line 10 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXhvYFwQwoornI7cza:-KbXhvYGFZighmWfYhCO:bfr5hxs) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/concurrent/async_queue-test.cc#L10)):*
> ```cpp
> #include <string>
> 
> #include "hittop/concurrent/latch.h"
> ```

Not used?

---

*[hittop/concurrent/async_queue-test.cc, line 13 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXhwZrrW0ngkdtPv0c:-KbXhwZsIw3WQvkJWvDE:bfr5hxs) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/concurrent/async_queue-test.cc#L13)):*
> ```cpp
> 
> using hittop::concurrent::AsyncQueue;
> using hittop::concurrent::Latch;
> ```

Not used?

---

*[hittop/concurrent/callback_target-test.cc, line 169 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXjByuwbcaTLQfe1h5:-KbXjByuwbcaTLQfe1h6:belk1xd) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/concurrent/callback_target-test.cc#L169)):*
> ```cpp
> 
> TEST(CallbackTargetTest, OneShotZeroArgsDispatchLater) {
>   boost::asio::io_service io;
> ```

A bunch of these test cases have the same setup; consider making into a fixture and using TEST_F()

---

*[hittop/concurrent/callback_target-test.cc, line 230 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXj3C16YSkdx3nbKC4:-KbXj3C16YSkdx3nbKC5:bog2m04) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/concurrent/callback_target-test.cc#L230)):*
> ```cpp
> TEST(CallbackTargetTest, OneShotZeroArgsPost) {}
> 
> TEST(CallbackTargetTest, Lambdas) {
> ```

This doesn't test anything in the plan, nor does it reference CallbackTarget

---

*[hittop/concurrent/callback_target.h, line 61 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXjaCVIlVZMXQujqXw:-KbXjaCVIlVZMXQujqXx:bbxpns4) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/concurrent/callback_target.h#L61)):*
> ```objc
>     auto local_obj = std::move(obj_);
>     Scheduler::schedule(local_obj->get_strand(), [
>       obj = std::move(bound_obj), fn = fn_,
> ```

This is very similar to the code above... extract a common helper?

---

*[hittop/concurrent/latching_signal-test.cc, line 12 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXjrYzNI-5oOp_tf4q:-KbXjrYzNI-5oOp_tf4r:b-x25caq) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/concurrent/latching_signal-test.cc#L12)):*
> ```cpp
> 
> using hittop::concurrent::Latch;
> ```

Need test plan; this test suite seems incomplete.

---

*[hittop/concurrent/latching_signal.h, line 26 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXk-2elfMwBnZQLetb:-KbXk-2elfMwBnZQLetc:b-rrqyzs) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/concurrent/latching_signal.h#L26)):*
> ```objc
> private:
>   using ArgsTuple = std::tuple<typename std::decay<Args>::type...>;
>   using Signal = boost::signal<void(Args...)>;
> ```

Should be using signals2

---

*[hittop/concurrent/latching_signal.h, line 81 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXk43pZYxMSNSR8RrG:-KbXk43pZYxMSNSR8RrH:b-36gvku) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/concurrent/latching_signal.h#L81)):*
> ```objc
>   }
> 
>   // TODO - ConnectDeferred
> ```

Yes, please do ;-)

---

*[hittop/concurrent/latching_signal.h, line 89 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXkXhlzyFBYAOgtcwo:-KbXkXhlzyFBYAOgtcwp:b-l2lbs7) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/concurrent/latching_signal.h#L89)):*
> ```objc
>       auto &handler = boost::get<Handler>(state_);
>       handler(a...);
>     }
> ```

else ... throw?  What should be desired behavior when trying to "re-latch" a LatchingSignal?  Do we want to provide a "reset" operation?  Or just destroy/construct a new one?

---

*[hittop/concurrent/latching_signal.h, line 97 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXk89CIBilWQHgW7Au:-KbXk89CIBilWQHgW7Av:bo087yg) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/concurrent/latching_signal.h#L97)):*
> ```objc
>       std::unique_lock<std::mutex> lock(mutex_);
>       if (state_.which() == 0) {
>         auto handler = std::move(boost::get<Handler>(state_));
> ```

Move signal; can boost::signals2::signal objects be moved?

---

*[hittop/concurrent/latching_signal.h, line 111 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXkRvO9pLyqtVTfsWX:-KbXkRvO9pLyqtVTfsWY:b93l8kv) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/concurrent/latching_signal.h#L111)):*
> ```objc
>   const typename std::tuple_element<I, ArgsTuple>::type *arg() const {
>     std::unique_lock<std::mutex> lock(mutex_);
>     if (state_.which() == 1) {
> ```

Use visitor?

---

*[hittop/concurrent/latching_signal.h, line 120 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXkP52m258V_XjpQIg:-KbXkP52m258V_XjpQIh:b-hjjxnn) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/concurrent/latching_signal.h#L120)):*
> ```objc
>   boost::optional<ArgsTuple> args() const {
>     std::unique_lock<std::mutex> lock(mutex_);
>     if (state_.which() == 1) {
> ```

Use visitor here instead?

---

*[hittop/io/async_mutable_buffer_stream.h, line 19 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXkp23eojyH7Flh3t5:-KbXkp23eojyH7Flh3t6:b-85l15e) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/io/async_mutable_buffer_stream.h#L19)):*
> ```objc
> //  std::size_t space() const;
> //  void commit(std::size_t byte_count);
> //
> ```

Member typedefs: mutable_buffers_type

---

*[hittop/io/async_mutable_buffer_stream.h, line 20 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXkyZ4S9ghtwbEWC7S:-KbXkyZ4S9ghtwbEWC7T:b-f4uldb) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/io/async_mutable_buffer_stream.h#L20)):*
> ```objc
> //  void commit(std::size_t byte_count);
> //
> ```

Provide a concept checking base class (CRTP) here?

---

*[hittop/io/mutable_buffers_handler.h, line 12 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXlgDuS2vSi7NvIqss:-KbXlgDv-yZCM-X48zL_:b528yy6) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/io/mutable_buffers_handler.h#L12)):*
> ```objc
> namespace io {
> 
> // AsyncMutableBufferStream Concept
> ```

Remove this redundant comment block

---

*[hittop/io/mutable_buffers_handler.h, line 25 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXlDpatGIQgNBoAecD:-KbXlDpatGIQgNBoAecE:b-7s4sqq) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/io/mutable_buffers_handler.h#L25)):*
> ```objc
> //
> using MutableBuffersHandler = std::function<void(
>     const error_code &, cosnt std::vector<mutable_buffer> &)>;
> ```

const

---

*[hittop/io/mutable_buffers_handler.h, line 25 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXlFehYAwTMFcasdtO:-KbXlFehYAwTMFcasdtP:b-6ygl2x) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/io/mutable_buffers_handler.h#L25)):*
> ```objc
> //
> using MutableBuffersHandler = std::function<void(
>     const error_code &, cosnt std::vector<mutable_buffer> &)>;
> ```

use a static vector?

---

*[hittop/json/parse_visitor.h, line 58 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXlz4PfjAO9kpzHoAs:-KbXlz4Q9bPJG9nTyS7z:bqlspt1) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/json/parse_visitor.h#L58)):*
> ```objc
>         break;
>       default:
>         // TODO!!!
> ```

Please do!

---

*[hittop/json/parser-test.cc, line 27 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXmVcUUGjEwaL5-db_:-KbXmVcUUGjEwaL5-dba:b1xl3f8) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/json/parser-test.cc#L27)):*
> ```cpp
> namespace json = hittop::json;
> namespace grammar = hittop::json::grammar;
> ```

Write test plan; this suite is spotty at best.

---

*[hittop/json/types-test.cc, line 11 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXmovvJDoMrlfBQS2W:-KbXmovvJDoMrlfBQS2X:bl8ibh1) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/json/types-test.cc#L11)):*
> ```cpp
> 
> namespace json = hittop::json;
> ```

Please write test plan; we're only testing Visit here it seems.

---

*[hittop/parser/concat.h, line 41 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXnTLbp7DxHXoxuyRz:-KbXnTLbp7DxHXoxuyS-:b173mgu) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/parser/concat.h#L41)):*
> ```objc
>   auto operator()(const Range &input, Args &&... args) const
>       -> Fallible<decltype(std::begin(input))> {
>     auto first_result = Parse<First>(input, std::forward<Args>(args)...);
> ```

It's an error to perfectly forward the arguments twice (the first time consumes all rvalue references); please fix.

---

*[hittop/parser/either.h, line 28 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXngBFTmfJY2OM8nZo:-KbXngBFTmfJY2OM8nZp:b-rl43kx) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/parser/either.h#L28)):*
> ```objc
>   auto operator()(const Range &input, Args &&... args) const
>       -> Fallible<decltype(std::begin(input))> {
>     auto first_result = Parse<First>(input, std::forward<Args>(args)...);
> ```

Please fix: forwarding twice.

---

*[hittop/parser/repeat.h, line 25 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXoqtt5c1PGc4BtGD4:-KbXoqtt5c1PGc4BtGD5:b6cqtdj) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/parser/repeat.h#L25)):*
> ```objc
>     for (;;) {
>       auto result = Parse<Grammar>(boost::make_iterator_range(next, last),
>                                    std::forward<Args>(args)...);
> ```

Please fix: potentially forwarding rvalue refs multiple times here.

---

*[hittop/parser/unless.h, line 28 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXpCATGoXWnJJhFlqk:-KbXpCATGoXWnJJhFlql:b-92amgr) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/parser/unless.h#L28)):*
> ```objc
>       return {reject_result.consume(), ParseError::FAILED_CONDITION};
>     }
>     return Parse<DefaultGrammar>(input, std::forward<Args>(args)...);
> ```

Please fix: std::forward more than once.

---

*[hittop/util/first_match.h, line 68 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXpUn9WOKNpmQbfE0P:-KbXpUn9WOKNpmQbfE0Q:bbm1pbu) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/util/first_match.h#L68)):*
> ```objc
> };
> 
> template <typename... F> FirstMatchFunctor<F...> FirstMatch(F &&... f) {
> ```

TBD - should we decay 'F' here and provide another function, FirstMatchRef, which does not?

---

*[hittop/util/is_callable.h, line 14 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXq4_sK5u8s6CKSuM-:-KbXq4_sK5u8s6CKSuM0:bwmxm6c) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/util/is_callable.h#L14)):*
> ```objc
>   template <typename F>
>   static std::true_type Impl(decltype(
>       std::declval<F>()(std::forward<Args>(std::declval<Args &&>())...)) *);
> ```

redundant; declval already returns rvalue reference to T.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hittop/hittop/8)*

**Comment by hittop** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 26 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hittop/hittop/8)*

**Comment by tonyastolfi** [comment]
Review status: all files reviewed at latest revision, 26 unresolved discussions.

---

*[hittop/concurrent/callback_target-test.cc, line 169 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXjByuwbcaTLQfe1h5:-KdqI1qBSTpEBNQVtrpD:b-896fix) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/concurrent/callback_target-test.cc#L169)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

A bunch of these test cases have the same setup; consider making into a fixture and using TEST_F()
</blockquote></details>

Done.

---

*[hittop/concurrent/callback_target-test.cc, line 230 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXj3C16YSkdx3nbKC4:-KdqI4MsMvnQO8-neUBa:b9paahu) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/concurrent/callback_target-test.cc#L230)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

This doesn't test anything in the plan, nor does it reference CallbackTarget
</blockquote></details>

Keeping it, moving to CallbackTargetSanity test class.

---

*[hittop/concurrent/callback_target.h, line 61 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXjaCVIlVZMXQujqXw:-KdqLTNof--4Tn4zlWuW:b-896fix) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/concurrent/callback_target.h#L61)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

This is very similar to the code above... extract a common helper?
</blockquote></details>

Done.

---

*[hittop/concurrent/latching_signal-test.cc, line 12 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXjrYzNI-5oOp_tf4q:-KdqLsmlIQVX_3_y65x_:b4ubqc) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/concurrent/latching_signal-test.cc#L12)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

Need test plan; this test suite seems incomplete.
</blockquote></details>

Deferred: https://github.com/hittop/hittop/issues/9

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hittop/hittop/8)*

**Comment by tonyastolfi** [comment]
Review status: 40 of 48 files reviewed at latest revision, 26 unresolved discussions.

---

*[hittop/parser/concat.h, line 41 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXnTLbp7DxHXoxuyRz:-KdqMdGpUQ_xd9ymgPnH:b-896fix) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/parser/concat.h#L41)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

It's an error to perfectly forward the arguments twice (the first time consumes all rvalue references); please fix.
</blockquote></details>

Done.

---

*[hittop/parser/either.h, line 28 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXngBFTmfJY2OM8nZo:-KdqMm3sOJTFGwbKrpvp:b-896fix) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/parser/either.h#L28)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

Please fix: forwarding twice.
</blockquote></details>

Done.

---

*[hittop/parser/repeat.h, line 25 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXoqtt5c1PGc4BtGD4:-KdqMsXK8rbvXWPW4ua2:b-896fix) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/parser/repeat.h#L25)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

Please fix: potentially forwarding rvalue refs multiple times here.
</blockquote></details>

Done.

---

*[hittop/parser/unless.h, line 28 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXpCATGoXWnJJhFlqk:-KdqMxc8VOKyUCf54G-G:b-896fix) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/parser/unless.h#L28)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

Please fix: std::forward more than once.
</blockquote></details>

Done.

---

*[hittop/util/first_match.h, line 68 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXpUn9WOKNpmQbfE0P:-KdqNGG4-BlVMJY6KGFq:b-896fix) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/util/first_match.h#L68)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

TBD - should we decay 'F' here and provide another function, FirstMatchRef, which does not?
</blockquote></details>

Done.

---

*[hittop/util/is_callable.h, line 14 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXq4_sK5u8s6CKSuM-:-KdqNRQQa_GFstoGBd-I:b-896fix) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/util/is_callable.h#L14)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

redundant; declval already returns rvalue reference to T.  
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hittop/hittop/8)*

**Comment by hittop** [comment]
Reviewed 11 of 11 files at r3.
Review status: all files reviewed at latest revision, 22 unresolved discussions.

---

*[hittop/util/first_match.h, line 75 at r3](https://reviewable.io:443/reviews/hittop/hittop/8#-Ke_bnWvVg-6mZMjpmxZ:-Ke_bnWvVg-6mZMjpmx_:b-onzrp9) ([raw file](https://github.com/hittop/hittop/blob/29a469e5f291fbd529f50cbc11ea69b03f595cb9/hittop/util/first_match.h#L75)):*
> ```objc
> 
> template <typename... F> auto FirstMatchRef(F &&... f) {
>   return FirstMatchFunctor<F...>(std::forward<F>(f)...);
> ```

Should be FirstMatchFunctor<F&&...>

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hittop/hittop/8)*

**Comment by tonyastolfi** [comment]
Review status: 44 of 48 files reviewed at latest revision, 22 unresolved discussions.

---

*[hittop/concurrent/async_queue-test.cc, line 10 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXhvYFwQwoornI7cza:-Ke_r-ixYocFzRVA_HfU:b-896fix) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/concurrent/async_queue-test.cc#L10)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

Not used?
</blockquote></details>

Done.

---

*[hittop/concurrent/async_queue-test.cc, line 13 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXhwZrrW0ngkdtPv0c:-Ke_r04pJVXL1PzxxAri:b-896fix) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/concurrent/async_queue-test.cc#L13)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

Not used?
</blockquote></details>

Done.

---

*[hittop/concurrent/latching_signal.h, line 81 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXk43pZYxMSNSR8RrG:-Ke_gThR1QS_tt0VCjw-:b-896fix) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/concurrent/latching_signal.h#L81)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

Yes, please do ;-)
</blockquote></details>

Done.

---

*[hittop/concurrent/latching_signal.h, line 89 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXkXhlzyFBYAOgtcwo:-Ke_ec2SBvwKgkwmL5aH:b-q43lx1) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/concurrent/latching_signal.h#L89)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

else ... throw?  What should be desired behavior when trying to "re-latch" a LatchingSignal?  Do we want to provide a "reset" operation?  Or just destroy/construct a new one?
</blockquote></details>

Deferred to later.  Can always just destroy/construct for now.

---

*[hittop/concurrent/latching_signal.h, line 97 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXk89CIBilWQHgW7Au:-Ke_egC2I4N7OB6htk_b:bb77ufg) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/concurrent/latching_signal.h#L97)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

Move signal; can boost::signals2::signal objects be moved?
</blockquote></details>

Yes.

---

*[hittop/concurrent/latching_signal.h, line 111 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXkRvO9pLyqtVTfsWX:-Ke_ejxo2_QuUv0-Ln9k:baw6h9g) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/concurrent/latching_signal.h#L111)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

Use visitor?
</blockquote></details>

Bad idea in this case; shuttling the args around is annoying and there seems little point.  I'm just commenting for now.

---

*[hittop/concurrent/latching_signal.h, line 120 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXkP52m258V_XjpQIg:-Ke_esWHDgwZ6R3fnJS3:b-896fix) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/concurrent/latching_signal.h#L120)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

Use visitor here instead?
</blockquote></details>

Done.

---

*[hittop/io/async_mutable_buffer_stream.h, line 19 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXkp23eojyH7Flh3t5:-Ke_jX8IfJ_aME3YjxU7:b-896fix) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/io/async_mutable_buffer_stream.h#L19)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

Member typedefs: mutable_buffers_type
</blockquote></details>

Done.

---

*[hittop/io/async_mutable_buffer_stream.h, line 20 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXkyZ4S9ghtwbEWC7S:-Ke_jXywdCxJG6L_8lsi:b-896fix) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/io/async_mutable_buffer_stream.h#L20)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

Provide a concept checking base class (CRTP) here?
</blockquote></details>

Done.

---

*[hittop/io/mutable_buffers_handler.h, line 12 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXlgDuS2vSi7NvIqss:-Ke_kvgcgpRT3Jwmi8aE:b-896fix) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/io/mutable_buffers_handler.h#L12)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

Remove this redundant comment block
</blockquote></details>

Done.

---

*[hittop/io/mutable_buffers_handler.h, line 25 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXlDpatGIQgNBoAecD:-Ke_kv-pzZeqRnECNcYi:b-896fix) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/io/mutable_buffers_handler.h#L25)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

const
</blockquote></details>

Done.

---

*[hittop/io/mutable_buffers_handler.h, line 25 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXlFehYAwTMFcasdtO:-Ke_kuk0gcpiL6KTTA47:b-896fix) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/io/mutable_buffers_handler.h#L25)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

use a static vector?
</blockquote></details>

Done.

---

*[hittop/json/parse_visitor.h, line 58 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXlz4PfjAO9kpzHoAs:-Ke_r1cJ8JW2xi_nymrG:b-896fix) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/json/parse_visitor.h#L58)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

Please do!
</blockquote></details>

Done.

---

*[hittop/json/parser-test.cc, line 27 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXmVcUUGjEwaL5-db_:-Ke_fgUZbZwFsYxZmE17:b4643it) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/json/parser-test.cc#L27)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

Write test plan; this suite is spotty at best.
</blockquote></details>

Deferred: https://github.com/hittop/hittop/issues/11

---

*[hittop/json/types-test.cc, line 11 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXmovvJDoMrlfBQS2W:-Ke_fdeIsvfBKPyW9Go5:b4643is) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/json/types-test.cc#L11)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

Please write test plan; we're only testing Visit here it seems.
</blockquote></details>

Deferred: https://github.com/hittop/hittop/issues/10

---

*[hittop/parser/concat.h, line 41 at r1](https://reviewable.io:443/reviews/hittop/hittop/8#-KbXnTLbp7DxHXoxuyRz:-Ke_fkNPocLIEoOuCuLG:b-896fix) ([raw file](https://github.com/hittop/hittop/blob/c539a54605e44cbdda18745193b5379f7930eb92/hittop/parser/concat.h#L41)):*
<details><summary><i>Previously, tonyastolfi (Tony Astolfi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[hittop/util/first_match.h, line 75 at r3](https://reviewable.io:443/reviews/hittop/hittop/8#-Ke_bnWvVg-6mZMjpmxZ:-Ke_gAURv0Iaelntvuex:b-896fix) ([raw file](https://github.com/hittop/hittop/blob/29a469e5f291fbd529f50cbc11ea69b03f595cb9/hittop/util/first_match.h#L75)):*
<details><summary><i>Previously, hittop (HiTToP High-Performance HTTP) wrote…</i></summary><blockquote>

Should be FirstMatchFunctor<F&&...>
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hittop/hittop/8)*

**Comment by hittop** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hittop/hittop/8)*

**Pull request merged**
